version: '3.4'

services:
  usersmicroservice:
    container_name: users-microservice
    image: ${DOCKER_REGISTRY-}usersmicroservice
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports: 
      - 8001:80
    depends_on:
      - db
      - rabbitmq
  db:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin123aa1!
    volumes:
      - db-data:/var/opt/mssql/data/
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  db-data:
  rabbitmq-data: