CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(80) NOT NULL,
	[Password] NVARCHAR(100) NOT NULL,
	[IsDeleted] BIT DEFAULT 0
)
